### PR TITLE
Standardize package json fields - Closes #1215

### LINKED ISSUE #1215: Standardize package.json fields
Child of #672

### PR DESCRIPTION
**Pull request by ManuGowda**
Closes #1215

### CODE REVIEW

**Comment by karmacoma** [comment]
@willclarktech Not really. They are quite arbitrary, also mostly specific to an individual project.

**Comment by vitaly-t** [comment]
Just so, it is consistent, marking the package as private (`"private: true"`), while it is actually sitting in the public GitHub repository :wink:

**Comment by willclarktech** [comment]
@vitaly-t I believe `private` is set to `true` to prevent accidental publishing to the npm registry, since Core is not currently published there.
https://docs.npmjs.com/files/package.json#private

**Comment by vitaly-t** [comment]
@willclarktech I have double-checked that - [npm private package](https://docs.npmjs.com/files/package.json#private), and yes, you are right :+1: it should be left as is :wink: Good one! :smile:

**Pull request merged**
