### PR TITLE
change secret length upper limit to utilize BIP-32

### PR DESCRIPTION
**Pull request by 34ro**
This PR change secret length upper limit to 215.
Current secret length limit is 100. It is assumed to use 12 words.
On the other hand, 24 words (contains 256 bit information) is go well together with BIP-32.
BIP-32 enable to create secret key from one key safely.
For this, HMAC-SHA512 hash is splited 256 bit chain code and 256 bit secret key.
So 256 bit is good number to utilize BIP-32 secret key.
English word is 8 char. 8 * 24 + 23 = 215

### CODE REVIEW

**Comment by Isabello** [comment]
This change will not be compatible in lisk-ui. First example but this was the first that came to mind. 

```
    $scope.login = function (pass, remember) {
        if (pass.trim().split(/\s+/g).length < 12) {
            $scope.errorMessage = 'Passphrase must consist of 12 or more words.';
            return;
        }
        if (pass.length > 100) {
            $scope.errorMessage = 'Passphrase must contain less than 100 characters.';
            return;
        }
        if (!Mnemonic.isValid(pass)) {
            $scope.errorMessage = 'Passphrase must be a valid BIP39 mnemonic code.';
            return;
        }
```
https://github.com/LiskHQ/lisk-ui/blob/development/js/controllers/passphraseController.js#L23

**Comment by 34ro** [comment]
yes. I know it.
For keeping compatibility,  change server side validation at the beginning

**Comment by 34ro** [comment]
But I think 256 bit secret key is not nessesaly for human user.

**Comment by fix** [comment]
Well, there is no limitation on the core code, the limitation and BIP39 enforcement is only performed on lisk-ui.

On the core the public key/private key are 512bits length using HMAC-SHA512

Please open raise this issue on lisk-ui instead

**Pull request closed without merging**
