### PR TITLE
Use src/index.js in Dockerfile and docker-compose.yml - Closes #3039

### LINKED ISSUE #3039: Update docker configuration to match with current structure
### Expected behavior
Docker configuration points to the updated entry point (from "/home/lisk/lisk/app.js" to "/home/lisk/lisk/src/index.js":
### Actual behavior
Docker configuration points to the outdated entry point. 
### Which version(s) does this affect? (Environment, OS, etc...)
`1.6.0`

### PR DESCRIPTION
**Pull request by ghost**
### What was the problem?
`Dockerfile` and `docker/docker-compose.yml` were pointing to `app.js` which has been renamed to `src/index.js`.

### How did I fix it?
Modified the above-mentioned files.

### How to test it?
Build docker image and run it; make sure the application starts properly.

### Review checklist

* The PR resolves #3039
* All new code is covered with unit tests
* All new code was formatted with Prettier
* Linting passes
* Tests pass
* Commit messages follow the [commit guidelines](CONTRIBUTING.md#git-commit-messages)
* Documentation has been added/updated

### CODE REVIEW

**Review by diego-G — DISMISSED** [review]

**Comment by ManuGowda** [comment]
@fchavant we discussed in our last meeting about keeping it to `npm start` so that we can avoid such changes in the future. I agree that you mentioned about `npm` being included in the build and its an issue, but just wanted to get a clarification that we are considering that approach.

**Comment by fchavant** [comment]
@ManuGowda I followed the instructions from #3039 and did not consider using `npm start`; what would be the benefit?

**Comment by ManuGowda** [comment]
> @ManuGowda I followed the instructions from #3039 and did not consider using `npm start`; what would be the benefit?

The benefit would be you need not worry in the future if they change it from `index.js` to something else and we can maintian the same in commander or wherever we use it. @shuse2 what's your take?

**Comment by shuse2** [comment]
I think adding to `npm start` is good. it's a standard in node projects, and always have one entry point to the application

**Comment by fchavant** [comment]
@ManuGowda @shuse2 now using `npm start`

**Review by diego-G — APPROVED** [review]

**Review by ManuGowda — APPROVED** [review]

**Review by shuse2 — APPROVED** [review]

**Review by psychopenguin — APPROVED** [review]

**Review by MaciejBaj — APPROVED** [review]

**Pull request merged**
