### PR TITLE
Unify callback position - Closes #576

### LINKED ISSUE #576: Unify callback position
There are some places in `\app.js` where the call style is `new Object(scope, cb)` and others is  `new Object(cb, scope)`
Callback function should be placed at the last position in arguments of a function.

### PR DESCRIPTION
**Pull request by oleblaesing**
Refactored `app.js` module class instance creator, using callback function as the second parameter for the modules.

I'm not sure if I have forgotten anything important, please let me know if I can improve this PR. Thank you!

### CODE REVIEW

**Comment by karmacoma** [comment]
Closes #576

**Comment by Isabello** [comment]
@karmacoma i think this can go into 0.9.1 what do you think?

**Comment by karmacoma** [comment]
@Isabello Ok 👍

**Comment by LucasIsasmendi** [comment]
Hi @oleblaesing, thanks for your help with this PR, could you please also check the test folder?, We need to unify callback position there, like this one: https://github.com/LiskHQ/lisk/blob/development/test/common/initModule.js#L91

**Comment by oleblaesing** [comment]
@LucasIsasmendi Yup! Thanks for the review. I will fix and verify the tests soon. :)

**Comment by karmacoma** [comment]
Moved to `1.0.0` milestone until tests covered.

**Comment by oleblaesing** [comment]
Thank you for you feedback! I will work on the improvements in some of the next weekends. :)

**Comment by Isabello** [comment]
PR needs to have conflicts resolved so we can review it once again @oleblaesing

**Comment by Isabello** [comment]
Thank you for this PR but its aged out of applicability at this point. Feel free to reimplement and resend in the future with passing tests.

**Pull request closed without merging**
