### PR TITLE
Make Access-Control-Allow-Origin header configurable - Closes #1973

### LINKED ISSUE #1973: Make Access-Control-Allow-Origin header configurable

### PR DESCRIPTION
**Pull request by nazarhussain**
### What was the problem?
CORS origin and methods were not configureable from json file. 

### How did I fix it?
Moved the confirmation from yml file to json configuration file. 

### How to test it?
Run the unit test for cors_fititng. 

### Review checklist

* The PR solves #1973
* All new code is covered with unit tests
* All new code was formatted with Prettier
* Linting passes
* Tests pass
* Commit messages follow the [commit guidelines](CONTRIBUTING.md#git-commit-messages)
* Documentation has been added/updated

### CODE REVIEW

**Comment by fchavant** [comment]
Can the header be disabled (not returned at all)? By setting `origin` to `''` maybe?

**Comment by nazarhussain** [comment]
You mean disabling the cross origin requests completely? You can do this by adding an empty string to `origin` and empty array to `methods`. This will block all HTTP calls from cross origin.

**Comment by fchavant** [comment]
Can we set `origin` to `false` as per the documentation to disable CORS entirely?

**Comment by nazarhussain** [comment]
Let me update the config schema to allow boolean value, then you can set either to `true` or `false`.

**Pull request merged**
