### PR TITLE
DB Layer restructuring #1306

### PR DESCRIPTION
**Pull request by vitaly-t**
Only the immediate fix, as the whole thing should be rewritten later, down the road, because mixing up `async.series` with callbacks + promises is a recipe for disaster.

### CODE REVIEW

**Comment by vitaly-t** [comment]
This probably should not be merged till #1303 is addressed, so there are at least some tests for the change.

**Comment by vitaly-t** [comment]
I shouldn't have done it in the same branch, but here's the initial changes for #1306

**Comment by vitaly-t** [comment]
@karmacoma Would be nice not to keep this change here, because it will quickly accumulate conflicts with other changes.

**Comment by karmacoma** [comment]
Thanks @vitaly-t. We will merge changes towards #1306 immediately, and defer changes towards #1297 until test coverage is in place.

**Comment by karmacoma** [comment]
@vitaly-t Please see the following test failures resulting from the restructuring:

```
> mocha "test/unit/sql/memAccountsProtection.js"

  1) "before all" hook
  2) "after all" hook

  0 passing (37ms)
  2 failing

  1) "before all" hook:
     QueryFileError: Error: ENOENT: no such file or directory, open '/Users/Oliver/GitHub/LiskHQ/lisk-development/db/sql/runtime.sql'
      at QueryFileError.Error (native)
      at new QueryFileError (node_modules/pg-promise/lib/errors/queryFile.js:41:24)
      at QueryFile.prepare (node_modules/pg-promise/lib/queryFile.js:203:21)
      at Database.$query (node_modules/pg-promise/lib/query.js:52:19)
      at Database.<anonymous> (node_modules/pg-promise/lib/query.js:229:23)
      at config.$npm.connect.pool.then.db (node_modules/pg-promise/lib/database.js:286:42)

  2) "after all" hook:
     TypeError: Cannot read property 'query' of undefined
      at Object.deleteAccount (test/unit/sql/memAccountsProtection.js:98:5)
      at Context.<anonymous> (test/unit/sql/memAccountsProtection.js:111:10)
```

**Pull request merged**
