### PR TITLE
Remove istanbul-middleware module - Closes #1999

### LINKED ISSUE #1999: Move istanbul-middleware to devDependencies
### Expected behavior
Snyk warns about dependencies used in production.

### Actual behavior
`istanbul-middleware` is a development dependency.

### PR DESCRIPTION
**Pull request by diego-G**
### What was the problem?

Snyk is continuously warning about that unmaintained module. 

### How did I fix it?
Decision is to remove the library due to the provided feature is useless.

### Review checklist

* The PR solves #1999
* All new code is covered with unit tests
* All new code was formatted with Prettier
* Linting passes
* Tests pass
* Commit messages follow the [commit guidelines](CONTRIBUTING.md#git-commit-messages)
* Documentation has been added/updated

### CODE REVIEW

**Comment by SargeKhan** [comment]
As far as I remember we gather API coverage in Jenkins as well, so we might want to remove the corresponding code there. And please create a new issue for gathering coverage using NYC as I still think it's a relatively important metric for code quality.

**Comment by diego-G** [comment]
@SargeKhan , https://github.com/LiskHQ/lisk/issues/1217 should be addressed following your comment

**Comment by MaciejBaj** [comment]
https://github.com/LiskHQ/lisk/issues/1999#issuecomment-387068076

**Comment by diego-G** [comment]
Close in favour of PR #2007

**Pull request closed without merging**
