### PR TITLE
Logic.account.get rank not working - Closes #1310

### LINKED ISSUE #1310: Logic.account.get rank not working
~Parent #1293~

### Expected behavior

The field rank should show the last position (rank = 102) and default value should be null

### Actual behavior
rank = 1

### Steps to reproduce

Execute `npm run mocha test/functional/system/blocks/chain.deleteLastBlock.js` on 1.0.0 branch with only `(type 2) register delegate`

### PR DESCRIPTION
**Pull request by LucasIsasmendi**
### How did I fix it?
1. Get the delegates from `mem_accounts` table.
2. Order them by quantity of votes descending and, in case of repetition, by publicKey ascending.
3. Add row number.
4. Get the row number for specific address.

### Review checklist

* The PR solves #1310 
* All new code is covered with unit tests
* Linting passes
* Tests pass
* Commit messages follow the [commit guidelines](CONTRIBUTING.md#git-commit-messages)
* Documentation has been added/updated

### CODE REVIEW

**Comment by robladbrook** [comment]
Hi @LucasIsasmendi - the approach you've taken with an inline sub-query looks valid, but could potentially be much more performant by using a view:

```sql
CREATE VIEW ranked_mem_accounts AS
SELECT *, row_number() OVER (ORDER BY "vote" DESC, "publicKey" ASC) as rank   	   
FROM mem_accounts
```

```sql
-- example:
select address, rank from ranked_mem_accounts where = 'blah'
```

This means that you aren't running the rank sub-query for every row in the result set, plus it allows your expression to be as simple as `expression: '(a."rank")::int'`

Just a thought! :)

**Comment by LucasIsasmendi** [comment]
Thanks @robladbrook , we will check the view approach

**Comment by vitaly-t** [comment]
There are also [Materialized Views](https://www.postgresql.org/docs/9.6/static/rules-materializedviews.html) in PostgreSQL ;)

**Comment by LucasIsasmendi** [comment]
Thanks @vitaly-t , we should provide some kind of benchmark that compares all options to support our decision regarding best performant option (currently 3), any ideas?

**Comment by 4miners** [comment]
Test are failing because:
- https://github.com/LiskHQ/lisk/blob/5d397bda7a3c2386b61b59d8479cf8c4c325c26e/test/unit/logic/account.js#L284-L285 We try get list of all accounts, we call `getAll` without limit (so default limit of `101` is applied). But we have `103` accounts in `mem_accounts` table, so we don't get all accounts (only `101` if `103`).
- https://github.com/LiskHQ/lisk/blob/5d397bda7a3c2386b61b59d8479cf8c4c325c26e/test/unit/logic/account.js#L357-L360
https://github.com/LiskHQ/lisk/blob/5d397bda7a3c2386b61b59d8479cf8c4c325c26e/test/unit/logic/account.js#L372-L375 We call `getAll` with requested field `username`. But if `username` is `NULL` that function skips those records, so compare fails.

So, tests are not reliable and probably behavior of `getAll` has changed.

**Comment by karmacoma** [comment]
This PR has the following failing tests, locally and on Jenkins.

```
  53 passing (5s)
  2 failing

  1) account
       getAll
         should ignore limit when below 1:

      Uncaught AssertionError: expected [ Array(101) ] to deeply equal [ Array(101) ]
      + expected - actual

         {
           "username": "genesis_36"
         }
         {
      -    "username": "genesis_37"
      -  }
      -  {
           "username": "genesis_38"
         }
         {
           "username": "genesis_39"
--
         }
         {
           "username": "genesis_99"
         }
      +  {
      +    "username": [null]
      +  }
       ]
      
    at Immediate.<anonymous> (test/unit/logic/account.js:362:20)
  

  2) account
       getAll
         should ignore offset when below 1:

      Uncaught AssertionError: expected [ Array(101) ] to deeply equal [ Array(101) ]
      + expected - actual

         {
           "username": "genesis_36"
         }
         {
      -    "username": "genesis_37"
      -  }
      -  {
           "username": "genesis_38"
         }
         {
           "username": "genesis_39"
--
         }
         {
           "username": "genesis_99"
         }
      +  {
      +    "username": [null]
      +  }
       ]
      
    at Immediate.<anonymous> (test/unit/logic/account.js:377:20)
```

**Pull request merged**
