### PR TITLE
Apply lisk eslint config - Closes #1207

### LINKED ISSUE #1207: Apply our eslint config
Child of #672 
Wait for https://github.com/LiskHQ/lisk/issues/1209
This will touch most files so timing will be important. It may also push us in the direction of substantive changes (which we may or may not want to ignore for now).

This issue should also cover updating the eslint config file, and moving test-specific config into a config file in the test directory.

### PR DESCRIPTION
**Pull request by ManuGowda**
### What was the problem?
Lisk core currently using basic eslint config which does not include most of the standard eslint rules, as part of this pull request we are going to extend `eslint-config-lisk-base` and implement the eslint rules.
### How did I fix it?
Included `.eslintrc.json` at root and `.eslintrc.json` in the test directory for test specific rules.
Introducing `lint` and `lint:fix` npm run scripts and `lint` runs against git `precommit` and `prepush`
### How to test it?
`npm run lint` to see all the lint issues.
`npm run lint:fix` will automatically fix certain issues.
### Review checklist

* The PR solves #1207 
* All new code is covered with unit tests
* Linting passes
* Tests pass
* Commit messages follow the [commit guidelines](CONTRIBUTING.md#git-commit-messages)
* Documentation has been added/updated

### CODE REVIEW

**Comment by vitaly-t** [comment]
I love the changes! :smile:

My only concern is with huge changes of `function` into `=>`, as this change affects interpretation of `this` context inside the callback. Hopefully, nothing got broken :wink:

**Comment by ManuGowda** [comment]
@vitaly-t I agree with you, I have done thorough testing of the PR and I also believe its a huge change, but at some point, we have to fix the code and make it cleaner, I believe we have lot of rules to cover ahead which I have turned off just because they are to many errors and we all can work together and slowly turn the rules one by one and fix them 😄

**Comment by willclarktech** [comment]
@vitaly-t I'm pretty sure ESLint doesn't try to convert functions to arrow functions in cases where the context will be an issue.

**Comment by ManuGowda** [comment]
@will those two warnings are mocha test suites with the same name, since the tests using template literals for suites description it looks the same but eslint considering them as a warning. whoever is going refactor those tests can later update the suites name properly, I have addressed the eslint config for specific files.

**Comment by will** [comment]
> @will those two warnings are mocha test suites with the same name, since the tests using template literals for suites description it looks the same but eslint considering them as a warning. whoever is going refactor those tests can later update the suites name properly, I have addressed the eslint config for specific files.

thanks, but also no thanks

**Pull request merged**
